// One source for the response headers: the `_headers` file Cloudflare applies to
// static assets is generated from here at build time, and the Workers set the
// same security headers on every response they build themselves, because the
// asset layer's rules never touch a Worker response.

const COMMON_HEADERS: Readonly<Record<string, string>> = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
};

export const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  ...COMMON_HEADERS,
  'Content-Security-Policy': [
    "default-src 'self'",
    "script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://www.googletagmanager.com",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: https://*.google-analytics.com https://www.googletagmanager.com",
    "font-src 'self'",
    "media-src 'self'",
    "connect-src 'self' https://cloudflareinsights.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    'upgrade-insecure-requests',
  ].join('; '),
};

export const ADMIN_SECURITY_HEADERS: Readonly<Record<string, string>> = {
  ...COMMON_HEADERS,
  'Content-Security-Policy': [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self'",
    "connect-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join('; '),
};

// Angular renames every bundle and every CSS-referenced file on each change, so
// those live in the browser cache forever; files copied from public/ keep their
// names between releases, so they are kept for a day and revalidated by ETag.
const IMMUTABLE = 'public, max-age=31536000, immutable';
const DAILY = 'public, max-age=86400, stale-while-revalidate=604800';
const cached = (cacheControl: string): Readonly<Record<string, string>> => ({
  'Cache-Control': cacheControl,
});
// The PDF renderer loads the fonts from a page with no origin, and fonts are CORS-checked.
const CORS_ANY_ORIGIN = { 'Access-Control-Allow-Origin': '*' } as const;
export const ASSET_RULES: readonly (readonly [
  pattern: string,
  headers: Readonly<Record<string, string>>,
])[] = [
  ['/*.js', cached(IMMUTABLE)],
  ['/*.css', cached(IMMUTABLE)],
  ['/media/*', cached(IMMUTABLE)],
  ['/fonts/*', { ...cached(DAILY), ...CORS_ANY_ORIGIN }],
  ['/images/*', cached(DAILY)],
  ['/video/*', cached(DAILY)],
  ['/icons/*', cached(DAILY)],
];

function applyHeaders(response: Response, headers: Readonly<Record<string, string>>): Response {
  const secured = new Response(response.body, response);
  for (const [name, value] of Object.entries(headers)) {
    if (!secured.headers.has(name)) secured.headers.set(name, value);
  }
  return secured;
}

/** Adds the site's security headers to a Worker response; existing headers win. */
export function withSecurityHeaders(response: Response): Response {
  return applyHeaders(response, SECURITY_HEADERS);
}

/** Adds the admin panel's security headers to a Worker response; existing headers win. */
export function adminSecurityHeaders(response: Response): Response {
  return applyHeaders(response, ADMIN_SECURITY_HEADERS);
}

/** The `_headers` file for the static-asset layer, in Cloudflare's rule syntax. */
export function renderHeadersFile(): string {
  const security = Object.entries(SECURITY_HEADERS)
    .map(([name, value]) => `  ${name}: ${value}`)
    .join('\n');
  const assets = ASSET_RULES.map(
    ([pattern, headers]) =>
      `${pattern}\n${Object.entries(headers)
        .map(([name, value]) => `  ${name}: ${value}`)
        .join('\n')}`,
  ).join('\n');
  return `# GENERATED by scripts/finalize.ts from workers/shared/security-headers.ts. Do not edit.
# Response headers for the static assets; the Workers set the same ones themselves.

/*
${security}

${assets}
`;
}
